---
title: "8_mixOmics_DIABLO"
author: "Sarah HUET"
date: "2021 M03 10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(phyloseq)
library(mixOmics)
library(tibble)
library(dplyr)
library(tidyr)
```

# Input Data

```{r wrangle data}
# choose the right phyloseq object
tmp_ps0 = ps_16S_micro

# OTU table
## calculate relative abundance
tmp_ps = transform_sample_counts(tmp_ps0, function(x) x / sum(x))
tmp_otu_table = tibble("sample" = as.numeric(sample_names(tmp_ps))) %>%
  bind_cols(t(tmp_ps@otu_table@.Data))

# Diversity metrics table
tmp_div_table = div_metrics$observed_species %>%
  rename(observed_species = value) %>%
  left_join(.,div_metrics$PD_whole_tree) %>%
  rename(PD_whole_tree = value) %>%
  left_join(.,div_metrics$simpson_reciprocal) %>%
  rename(simpson_reciprocal = value) %>%
  left_join(.,div_metrics$wunifrac) %>%
  rename(wunifrac = value) %>%
  group_by(sample) %>%
  summarise(observed_species = mean(observed_species,na.rm = T),
            PD_whole_tree = mean(PD_whole_tree,na.rm = T),
            simpson_reciprocal = mean(simpson_reciprocal,na.rm = T),
            wunifrac = mean(wunifrac,na.rm = T)) %>% ungroup()

```

```{r remove missing values}

# check if there not missing values
table(is.na(tmp_otu_table))
table(is.na(tmp_div_table))

# no value missing
```

```{r create dataset}

# arrange table to have the same pool order
tmp_data_all <- tmp_otu_table %>%
  left_join(.,tmp_div_metric) %>%
  left_join(.,tmp_ps@sam_data)

# merge the three tables into a single object
tmp_data = list(OTU = tmp_data_all[,colnames(tmp_otu_table)[-1]],
                diversity_metrics = tmp_data_all[,colnames(tmp_div_table)[-1]])

# check dimension
lapply(tmp_data, dim)

# extract treatment names as factors
tmp_ttt <- factor(tmp_data_all$treatment)

summary(tmp_ttt) # number of pool by treatment
length(tmp_ttt) # total number of observations

```

# Parameter choice

```{r Design}

# create the design matrix 
tmp_design = matrix(0.1, ncol = length(tmp_data), nrow = length(tmp_data), 
                dimnames = list(names(tmp_data), names(tmp_data)))
diag(tmp_design) = 0

tmp_design

```

```{r Tuning the number of components}

tmp_sgccda.res = block.splsda(X = tmp_data, Y = tmp_ttt, ncomp = 2, 
                           design = tmp_design)

set.seed(123) # for reproducibility, only when the `cpus' argument is not used
# this code takes a couple of min to run
tmp_perf.diablo = perf(tmp_sgccda.res, validation = 'Mfold', folds = 4, nrepeat = 10)

#tmp_perf.diablo  # lists the different outputs
plot(tmp_perf.diablo) 

tmp_perf.diablo$choice.ncomp$WeightedVote

# select the number of component
tmp_ncomp = tmp_perf.diablo$choice.ncomp$WeightedVote["Overall.BER", "centroids.dist"]

```

```{r Tuning keepX (create test dataset)}

tmp_test.keepX = list (OTU = c(1:5,
                               sort(sample(1:ntaxa(tmp_ps),size = ntaxa(tmp_ps)/25,prob = taxa_sums(tmp_ps)))),
                       diversity_metrics = c(2,4))

summary(tmp_test.keepX)
```

```{r Tuning keepX (~1h30)}

#set.seed(123) # for reproducibility, only when the `cpus' argument is not used

tmp_tune.TCGA = tune.block.splsda(X = tmp_data, Y = tmp_ttt, ncomp = tmp_ncomp, 
                              test.keepX = tmp_test.keepX, design = tmp_design,
                              validation = 'Mfold', folds = 10, nrepeat = 1,
                              #cpus = 2, 
                              dist = "centroids.dist")


tmp_list.keepX = tmp_tune.TCGA$choice.keepX
tmp_list.keepX

# to manually input parameters from this tuning step
#tmp_list.keepX = list(otu = c(42,165,505,485,485), activity = c(2,4,3,2,6), qPCRs = c(4,2,2,4,1))

```

## Final model

```{r select a tune model}

tmp_list.keepX = tmp_tune.TCGA$choice.keepX
tmp_list.keepX

tmp_ncomp = as.numeric(length(tmp_list.keepX[[1]]) ) 
tmp_ncomp

tmp_sgccda.res = block.splsda(X = tmp_data, Y = tmp_ttt, ncomp = tmp_ncomp,
                              keepX = tmp_list.keepX, design = tmp_design)
#tmp_sgccda.res   # list the different functions of interest related to that object

tmp_sgccda.res$design

# OTU variables selected on component 1
length(selectVar(tmp_sgccda.res, block = 'otu', comp = 1)$otu$name)



```

## Network

```{r panel 5}

tmp_diabloPanel <- mapply(function(x, y){
  c(x, y)
}, x = lapply(selectVar(tmp_sgccda.res, comp = 1), function(i) unlist(i[[1]])),
y = lapply(selectVar(tmp_sgccda.res, comp = 2), function(i) unlist(i[[1]])))

sapply(tmp_diabloPanel, length)
## only keep unique features
tmp_diabloPanel <- lapply(tmp_diabloPanel, unique)
sapply(tmp_diabloPanel, length)


tmp_diabloPanel2 <- list(OTU=tmp_diabloPanel[[1]],
                         diversity_metrics=tmp_diabloPanel[[2]])

sapply(tmp_diabloPanel2, length)

rm(tmp_diabloPanel)

```

```{r extract network}

# correlation matrix
tmp_corMat <- mapply(function(x, y){
  y[, x]
}, x = tmp_diabloPanel2, y = tmp_data, SIMPLIFY = FALSE) %>%
  do.call(cbind, .) %>%
  cor

# rename properly the column
colnames(tmp_corMat) <- rownames(tmp_corMat) <- gsub('(OTU|diversity_metrics)[:.:]',"",colnames(tmp_corMat))

# remove duplicates
tmp_corMat[lower.tri(tmp_corMat)] <- 0
diag(tmp_corMat) <- 0

# extract and filter correlations
tmp_links <- tmp_corMat %>%
  as.data.frame() %>%
  mutate(to = rownames(.)) %>%
  gather(from, cor, -to) %>%
  # keep only correlations <-0.6 or >0.6
  filter(abs(cor) > 0.6) %>%
  mutate(
    OTU_in_susp = case_when(
      to %in% taxa_names(ps_16S_susp_manip) ~ "to_in_manip_susp",
      .default = "not_in_manip_susp"
    )
  )

# extract node names
tmp_nodes = data.frame(id = unique(c(tmp_links$to, tmp_links$from)))

# wirte a csv file to import the network into cytoscape software
write.csv(tmp_links,"cytoscape_diablo_network.csv",row.names = F,quote = F)

```

