---
title: "7_soil_properties_and_functions"
author: "Sarah HUET"
date: "2021 M03 10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(dplyr)

# remove all temporary objects from your environment
rm(list = names(.GlobalEnv)[grep("tmp",names(.GlobalEnv))])

```

# functions
```{r choose your data}

# choose a variable from Data-function between:
## soil properties: "humidity" or "pH"
## N-cycling activities: "NO3", "NH4", "Ntot"
## abundance of microbial groups: "qPCR_16S"
tmp_function = "qPCR_16S" 

```

```{r wrangle data}

# select the chosen function


# keep sterile soil for pH and Nmin and Original soil for other functions
if (tmp_function %in% c("pH","NO3","NH4","Ntot")) {
  tmp_data = metadata_pool[,c("treatment","pool",tmp_function)]
  tmp_data = tmp_data[tmp_data$treatment != "T0",]
} else {
  tmp_data = metadata_sample
  #tmp_data = tmp_data[tmp_data$sample_type == "microcosm",]
  tmp_data = tmp_data[,c("treatment","sample",tmp_function)]
}

colnames(tmp_data)[3] <- "value"

```

```{r statistic test}
library(agricolae)
library(tibble)

# linear model
tmp_lm = lm(tmp_data$value ~ tmp_data$treatment, na.action = na.omit )
summary(tmp_lm)
# anova
anova(tmp_lm)
tmp_aov = aov(tmp_lm)
summary(tmp_aov)
# post hoc Tukey test
tmp_comp <- HSD.test(tmp_aov,'tmp_data$treatment',alpha = 0.05,group = T)
# tibble with statistical groups
tmp_stat = tibble("treatment"=rownames(tmp_comp[["groups"]]),
                  "mean"=tmp_comp[["groups"]][["tmp_data$value"]],
                  "stat_groups"=as.character(tmp_comp[["groups"]][["groups"]]))
# put a * for treatments in a different group than the control
tmp_stat[,"stat_dif_control"] <- " "

# select control
tmp_group_control <- unlist(strsplit(tmp_stat$stat_groups[tmp_stat$treatment == "C"],""))

for (i in tmp_stat$treatment) {
  tmp_group_treatment = unlist(strsplit(tmp_stat$stat_groups[tmp_stat$treatment == i],""))
  ifelse(length(intersect(tmp_group_control,tmp_group_treatment)) == 0,
         tmp_stat[tmp_stat$treatment == i,"stat_dif_control"] <- "*",
         tmp_stat[tmp_stat$treatment == i,"stat_dif_control"] <- " ")
  
}

rm(i)

```

```{r barplot stat with letters, width = 5.5,height = 6}
library(ggplot2)
library(dplyr)

tmp_plot_data = left_join(tmp_data,
                          Color_sets[Color_sets$set == "treatments",
                                     c("treatment","color","order")],
                          by = "treatment")
tmp_plot_stat = tmp_stat

tmp_ylim = c(0,max(tmp_data$value)*1.2)
tmp_ylim_stat = max(tmp_data$value)*1.1

tmp_plot_stat[,"stat_y"] <- tmp_ylim_stat

# plot
p <- ggplot(tmp_plot_data, aes(x = reorder(treatment,desc(order)),
                               y = value)) +
  stat_summary(geom = "bar", fun = mean, colour = "#333333",
               linetype = 1,
               fill = levels(reorder(tmp_plot_data$color,desc(tmp_plot_data$order))))+ 
  labs(x="Treatment", y= paste0("\n",tmp_function), title = tmp_function, color = "#333333")+
  #ylim(c(0,tmp_ylim))+
  coord_flip(ylim = tmp_ylim)+
  #scale_y_log10(expand = c(0,0), limits = c(1,max(tmp_ylim)*10))+
  #labs(x="Treatment", y= paste0("\n",tmp_index," (log10)"), title = tmp_index, color = "#333333")+
  theme_bw()+
  theme(title = element_text(face="bold", size=15),
        legend.position = "right",
        axis.title.x = element_text(face="bold", size=14), 
        axis.text.x  = element_text(vjust=0.5, size=12,angle = 0),
        axis.title.y = element_text(face="bold", size=14), 
        axis.text.y  = element_text(vjust=0.5, size=12),
        strip.text = element_text(face="bold", size=12),
        strip.background = element_rect(fill="white", colour="#333333",size=1.5))+
  stat_summary(geom = "linerange", fun.data = mean_se, width=0.5,color = "#333333" )+
  geom_text(data = tmp_plot_stat,
            #mapping = aes(label = stat_groups, y = stat_y*5, x=treatment),
            mapping = aes(label = stat_groups, y = stat_y, x=treatment),
            colour="#333333", size=10,inherit.aes = F, angle = 0,
            position = position_nudge(x = 0))
  
p

```

# qPCR

```{r suspensions}

tmp_function = "qPCR_16S" 

tmp_data = metadata_sample
tmp_data = tmp_data[tmp_data$sample_type == "suspension",]
tmp_data = tmp_data[,c("treatment","sample",tmp_function)]

tmp_susp = c("MAC_a1","MAC_a2","PEB_a1","PEB_a2")

tmp_loop = tibble()
for (i in tmp_susp) {
  
  tmp_d1 <- tmp_data$qPCR_16S[tmp_data$treatment == paste0("susp_",i)]*5/1000
  tmp_d2 <- tmp_d1*10/100
  tmp_d3 <- tmp_d1*10/1000
  
  tmp_df = tibble("treatment"=rep(paste0(i,c("d1","d2","d3")),each= 3),
                  "sample"=NA,
                  "qPCR_16S"= c(tmp_d1,tmp_d2,tmp_d3))
  
  tmp_loop <- rbind(tmp_loop,tmp_df)
  
}


tmp_data <- rbind(tmp_data,tmp_loop)
colnames(tmp_data)[3] <- "value"

tmp_data$value <- log10(tmp_data$value)

# remove non inoculated susp
#tmp_data <- tmp_data[!tmp_data$treatment %in% paste0("susp_",tmp_susp),]

```

```{r microcosm}

tmp_function = "qPCR_16S" 

tmp_data = metadata_sample
#tmp_data = tmp_data[tmp_data$sample_type %in% c("original_soil","microcosm"),]
tmp_data = tmp_data[tmp_data$sample_type == "microcosm",]
tmp_data = tmp_data[,c("treatment","sample",tmp_function)]

colnames(tmp_data)[3] <- "value"
tmp_data$value <- log10(tmp_data$value)



```

## plot with stats

```{r statistic test}
library(agricolae)
library(tibble)


# linear model
tmp_lm = lm(tmp_data$value ~ tmp_data$treatment, na.action = na.omit )
summary(tmp_lm)
# anova
anova(tmp_lm)
tmp_aov = aov(tmp_lm)
summary(tmp_aov)
# post hoc Tukey test
tmp_comp <- HSD.test(tmp_aov,'tmp_data$treatment',alpha = 0.05,group = T)
# tibble with statistical groups
tmp_stat = tibble("treatment"=rownames(tmp_comp[["groups"]]),
                  "mean"=tmp_comp[["groups"]][["tmp_data$value"]],
                  "stat_groups"=as.character(tmp_comp[["groups"]][["groups"]]))
# put a * for treatments in a different group than the control
tmp_stat[,"stat_dif_control"] <- " "

# select control
tmp_group_control <- unlist(strsplit(tmp_stat$stat_groups[tmp_stat$treatment == "C"],""))

for (i in tmp_stat$treatment) {
  tmp_group_treatment = unlist(strsplit(tmp_stat$stat_groups[tmp_stat$treatment == i],""))
  ifelse(length(intersect(tmp_group_control,tmp_group_treatment)) == 0,
         tmp_stat[tmp_stat$treatment == i,"stat_dif_control"] <- "*",
         tmp_stat[tmp_stat$treatment == i,"stat_dif_control"] <- " ")
  
}

rm(i)

```

```{r barplot stat with letters, width = 5.5,height = 6}
library(ggplot2)
library(dplyr)

tmp_plot_data = left_join(tmp_data,
                          Color_sets[Color_sets$set == "treatments",
                                     c("treatment","color","order")],
                          by = "treatment")
tmp_plot_stat = tmp_stat

tmp_ylim = c(0,max(tmp_data$value)*1.2)
tmp_ylim_stat = max(tmp_data$value)*1.1

tmp_plot_stat[,"stat_y"] <- tmp_ylim_stat

# plot
p <- ggplot(tmp_plot_data, aes(x = reorder(treatment,desc(order)),
                               y = value)) +
  stat_summary(geom = "bar", fun = mean, colour = "#333333",
               linetype = 1,
               fill = levels(reorder(tmp_plot_data$color,desc(tmp_plot_data$order))))+ 
  labs(x="Treatment", y= paste0("\n",tmp_function), title = tmp_function, color = "#333333")+
  coord_flip()+
  ylim(tmp_ylim)+
  #scale_y_log10(expand = c(0,0), limits = c(1,max(tmp_ylim[2])*10))+
  #labs(x="Treatment", y= paste0("\n",tmp_index," (log10)"), title = tmp_index, color = "#333333")+
  theme_bw()+
  theme(title = element_text(face="bold", size=15),
        legend.position = "right",
        axis.title.x = element_text(face="bold", size=14), 
        axis.text.x  = element_text(vjust=0.5, size=12,angle = 0),
        axis.title.y = element_text(face="bold", size=14), 
        axis.text.y  = element_text(vjust=0.5, size=12),
        strip.text = element_text(face="bold", size=12),
        strip.background = element_rect(fill="white", colour="#333333",size=1.5))+
  stat_summary(geom = "linerange", fun.data = mean_se, width=0.5,color = "#333333" )+
  geom_text(data = tmp_plot_stat,
            #mapping = aes(label = stat_groups, y = stat_y*5, x=treatment),
            mapping = aes(label = stat_groups, y = stat_y, x=treatment),
            colour="#333333", size=10,inherit.aes = F, angle = 0,
            position = position_nudge(x = 0))  
p


```

## without stat

```{r Table}

tmp_data = metadata_sample[,c("treatment","qPCR_16S")]

tmp_table = tmp_data %>% group_by(treatment) %>% summarise(Mean=mean(qPCR_16S),
                                                           SD=sd(qPCR_16S),
                                                           n=n(),
                                                           S.E. = SD / sqrt(n))

write.csv(tmp_table,"tmp.csv")


```

```{r plot suspensions}

# wrangle data



tmp_plot_data = left_join(tmp_data,
                          Color_sets[Color_sets$set == "treatments",
                                     c("treatment","color","order")],
                          by = "treatment")
tmp_plot_stat = tmp_stat

tmp_ylim = c(0,max(tmp_data$value)*1.2)
tmp_ylim_stat = max(tmp_data$value)*1.1

tmp_plot_stat[,"stat_y"] <- tmp_ylim_stat

# plot
p <- ggplot(tmp_plot_data, aes(x = reorder(treatment,desc(order)),
                               y = value)) +
  stat_summary(geom = "bar", fun = mean, colour = "#333333",
               linetype = 1,
               fill = levels(reorder(tmp_plot_data$color,desc(tmp_plot_data$order))))+ 
  labs(x="Treatment", y= paste0("\n",tmp_function), title = tmp_function, color = "#333333")+
  coord_flip()+
  scale_y_log10(expand = c(0,0), limits = c(1,max(tmp_ylim[2])*10))+
  #labs(x="Treatment", y= paste0("\n",tmp_index," (log10)"), title = tmp_index, color = "#333333")+
  theme_bw()+
  theme(title = element_text(face="bold", size=15),
        legend.position = "right",
        axis.title.x = element_text(face="bold", size=14), 
        axis.text.x  = element_text(vjust=0.5, size=12,angle = 0),
        axis.title.y = element_text(face="bold", size=14), 
        axis.text.y  = element_text(vjust=0.5, size=12),
        strip.text = element_text(face="bold", size=12),
        strip.background = element_rect(fill="white", colour="#333333",size=1.5))+
  stat_summary(geom = "linerange", fun.data = mean_se, width=0.5,color = "#333333" )
p


# export svg
ggsave(plot = p,
       filename = "tmp_fig.svg",
       width = 90,height = 130,units = "mm")

```


